config/routes.rb
Rails.application.routes.draw do
  resources :entities
  resources :dna_codes

  # Sitemap
  get '/sitemap.xml' => 'sitemaps#index', defaults: { format: 'xml' }

  # Feed
  get '/feed', to: 'feeds#rss', format: 'xml', as: :feed

  # Error pages
  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unacceptable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  # Admin dashboard
  namespace :admin do
    # Monitoring tools
    get 'monitoring', to: 'monitorings#index'
    resource :helloworld_job, only: [:create, :show]
    resource :migrate_data, only: [:edit, :update, :show]
    resource :versions, only: [:show]
    # CRUD our data
    resources :accounts
    resources :articles
    resources :editables
    resources :tags
    # Settings accessible to non-techies
    resources :settings, only: [:index, :update]
    # Home page of the admin
    root :to => "admin#index"
  end

  # Customer dashboard
  namespace :profile do
    root :to => "names#show"
    resource :name, only: [:show, :update]
    resource :danger, only: [:show]
    resource :preference, only: [:show, :update]
    resource :billing, only: [:show]
  end
  
  # Routes are protected under app/misc/rodauth_app.rb
  mount Sidekiq::Web => '/admin/monitor/jobs', :as => 'sidekiq'
  mount RailsDb::Engine => '/admin/monitor/db', :as => 'rails_db'

  # Public pages
  get "home/index"
  root to: "home#index"
  get "terms", to: "page#terms"
  get "about", to: "page#about"
  get "faq", to: "page#faq"
  get "credits", to: "page#credits"
  get "styleguide", to: "page#styleguide"
  get "pricing", to: "page#pricing"
  get "changelog", to: "page#changelog"

  # Blog
  namespace :blog do
    resources :tags, only: [:index, :show]
  end
  resources :blog, only: [:index, :show]

  # Test-mode only routes
  get "/get_last_email", to: "test#get_last_email" if Rails.env.test?
end

app/models/article.rb
class Article < ApplicationRecord
  
  validates :slug, presence: true, uniqueness: true
  validates_format_of :slug, with: /\A[-_A-Za-z0-9]+\z/, message: "invalid : alphanumeric characters only"

  validates :title, presence: true, uniqueness: true, length: {minimum: 5, maximum: 120}

  validates :image_url, allow_blank: true, format: { with: URI.regexp(%w[http https]), message: 'is not a valid URL' }

  # Many-to-many relationship between tags and articles
  has_many :markers
  has_many :tags, through: :markers

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::AdminController

  # Each and every action must be authorized
  before_action :authorize!

  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles
  def index
    @articles = Article.all
  end

  # GET /articles/1
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to([:admin, @article], notice: "Article was successfully created.", triggered_validation: true)
    else
      flash.now[:alert] = 'Article not created'
      render :new, status: :unprocessable_entity, locals: {triggered_validation: true}
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to admin_article_path(triggered_validation: true), notice: "Article was successfully updated."
    else
      flash.now[:alert] = 'Article not updated'
      render :edit, status: :unprocessable_entity, locals: {triggered_validation: true}
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to admin_articles_url, notice: "Article was successfully destroyed."
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:shortname, :slug, :kontent, :title, :description, :image_url, :publication_date, :is_published, tag_ids: [])
    end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/views/admin/articles/_action_create.html.erb
<div>
  <%= link_to new_admin_article_path, class: "d-flex justify-content-center align-items-center btn btn-primary btn-sm action-create-item"  do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
      <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"></path>
      <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"></path>
    </svg>
    <span class="ms-2">
      Create
    </span>
  <% end %>
</div>

app/views/admin/articles/_action_delete.html.erb
<div>
  <%= form_with url: admin_article_path(article.id), method: :delete, data: { turbo: false } do |form| %>
    <%= form.submit 'Delete', class: "admin-delete-item admin-destroy-item-white d-flex justify-content-center align-items-center btn btn-danger btn-sm shadow-none text-white ps-4" %>
  <% end %>
</div>

app/views/admin/articles/_action_edit.html.erb
<div>
  <%= link_to edit_admin_article_path(article), :class => "d-flex justify-content-center align-items-center btn btn-primary btn-sm shadow-none action-edit-item" do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
      <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"></path>
      <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"></path>
    </svg>
    <span class="ms-1">Edit</span>
  <% end %>
</div>

app/views/admin/articles/_action_index.html.erb
<div>
  <%= link_to admin_articles_path, class: "d-flex justify-content-center align-items-center btn btn-primary btn-sm action-list-item"  do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-card-list" viewBox="0 0 16 16">
        <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"></path>
        <path d="M5 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 5 8zm0-2.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm0 5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm-1-5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zM4 8a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm0 2.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0z"></path>
    </svg>
    <span class="ms-2">
      List
    </span>
  <% end %>
</div>

app/views/admin/articles/_action_show.html.erb
<div>
  <%= link_to [:admin, article], class: "d-flex justify-content-center align-items-center btn btn-primary btn-sm action-show-item"  do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
      <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"></path>
      <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"></path>
    </svg>
    <span class="ms-2">
      Show
    </span>
   <% end %>
</div>

app/views/admin/articles/_article.html.erb
<div id="<%= dom_id article %>">
</div>

app/views/admin/articles/_form.html.erb
<% triggered_validation = !!local_assigns[:triggered_validation] || !!params[:triggered_validation] %>
<% errors_h = @article.errors.to_hash %>

<%= form_with(model: [:admin, article]) do |form| %>

    <div class="form-group mb-1">
      <% is_valid_slug = triggered_validation && errors_h[:slug].blank? && @article.slug.present?  %>
      <% is_invalid_slug = !!errors_h[:slug]  %>
      <%= form.label "slug-input", 'Slug *', class: "mb-0 fw-600" %>
      <small id="hint_id_slug" class="form-text text-muted d-block my-0">
        Required - Will appear after /blog in the URL, i.e. /blog/my-article
      </small>
      <%= form.text_field 'slug', 
            value: @article.slug, 
            id: "slug-input", 
            placeholder: 'Example : my-article',
            class: "form-control #{"is-invalid" if is_invalid_slug} #{"is-valid" if is_valid_slug}", aria: ({ invalid: is_invalid_slug, describedby: "slug_message" } if triggered_validation) %> 
      <%= content_tag(:span, errors_h[:slug][0], class: "invalid-feedback", id: "slug_message") if is_invalid_slug %>
      <%= content_tag(:span, 'looks good !', class: "valid-feedback", id: "slug_message") if is_valid_slug  %>
    </div>

    <div class="form-group mb-1">
      <% is_valid_kontent = triggered_validation && errors_h[:kontent].blank? && @article.kontent.present?  %>
      <% is_invalid_kontent = !!errors_h[:kontent]  %>
      <%= form.label "kontent-input", 'Content', class: "mb-0 fw-600" %>
      <small id="hint_id_kontent" class="form-text text-muted d-block my-0">
        Optional, but recommended. Actual content of your article. Markdown, HTML, or plain text are accepted.
      </small>
      <div id="editorSection"></div>
      <%= form.text_field 'kontent', 
            value: @article.kontent, 
            id: "kontent-input", 
            style: "height: 0",
            class: "invisible mb-0 form-control #{"is-invalid" if is_invalid_kontent} #{"is-valid" if is_valid_kontent}", aria: ({ invalid: is_invalid_kontent, describedby: "kontent_message" } if triggered_validation) %> 
      <%= content_tag(:span, errors_h[:kontent][0], class: "invalid-feedback", id: "kontent_message", style: "margin-top:-.8rem") if is_invalid_kontent %>
      <%= content_tag(:span, 'looks good !', class: "valid-feedback", id: "kontent_message", style: "margin-top:-.8rem") if is_valid_kontent  %>
    </div>

    <div class="form-group mb-1">
      <% is_valid_title = triggered_validation && errors_h[:title].blank? && @article.title.present?  %>
      <% is_invalid_title = !!errors_h[:title]  %>
      <%= form.label "title-input", 'Title *', class: "mb-0 fw-600" %>
      <small id="hint_id_title" class="form-text text-muted d-block my-0">
        Required - Title will be shown in SEO results, and tab title of the browser.
      </small>
      <%= form.text_field 'title', 
            value: @article.title, 
            id: "title-input", 
            placeholder: 'Example : My Article Title',
            class: "form-control #{"is-invalid" if is_invalid_title} #{"is-valid" if is_valid_title}", aria: ({ invalid: is_invalid_title, describedby: "title_message" } if triggered_validation ) %> 
      <%= content_tag(:span, errors_h[:title][0], class: "invalid-feedback", id: "title_message") if is_invalid_title %>
      <%= content_tag(:span, 'looks good !', class: "valid-feedback", id: "title_message") if is_valid_title  %>
    </div>

    <div class="form-group mb-1">
      <% is_valid_description = triggered_validation && errors_h[:description].blank? && @article.description.present?  %>
      <% is_invalid_description = !!errors_h[:description]  %>
      <%= form.label "description-input", 'Description', class: "mb-0 fw-600" %>
      <small id="hint_id_description" class="form-text text-muted d-block my-0">
        Optional, but recommended : this will be shown in SEO result under the title
      </small>
      <%= form.text_field 'description', 
            value: @article.description, 
            id: "description-input", 
            class: "form-control #{"is-invalid" if errors_h[:description]} #{"is-valid" if is_valid_description}", aria: ({ invalid: is_invalid_description, describedby: "description_message" } if triggered_validation) %> 
      <%= content_tag(:span, errors_h[:description][0], class: "invalid-feedback", id: "description_message") if is_invalid_description %>
      <%= content_tag(:span, 'looks good !', class: "valid-feedback", id: "description_message") if is_valid_description  %>
    </div>

    <div class="form-group mb-1">
      <% is_valid_image_url = triggered_validation && errors_h[:image_url].blank? && @article.image_url.present?  %>
      <% is_invalid_image_url = !!errors_h[:image_url]  %>
      <%= form.label "image_url-input", 'Image URL', class: "mb-0 fw-600" %>
      <small id="hint_id_image_url" class="form-text text-muted d-block my-0">
        Optional. Image_url will appear when you share link on social media, for example. URL format only.
      </small>
      <%= form.text_field 'image_url', 
            value: @article.image_url, 
            id: "image_url-input", 
            placeholder: 'Example : https://image_url-service.com/myimage_url.png',
            class: "form-control #{"is-invalid" if errors_h[:image_url]} #{"is-valid" if is_valid_image_url}", aria: ({ invalid: is_invalid_image_url, describedby: "image_url_message" } if triggered_validation) %> 
      <%= content_tag(:span, errors_h[:image_url][0], class: "invalid-feedback", id: "image_url_message") if is_invalid_image_url %>
      <%= content_tag(:span, 'looks good !', class: "valid-feedback", id: "image_url_message") if is_valid_image_url  %>
    </div>

    <div class="form-group mb-4">
      <%= form.label "publication_date-input", 'Publication date', class: "mb-0 fw-600" %>
      <small id="hint_id_publication_date" class="form-text text-muted d-block my-0">
        Required. The date that will appear inside the blog article as the publication date.
      </small>
      <%= form.date_select 'publication_date', 
            start_year: 2000,
            end_year: Time.now.year,
            value: @article.publication_date, 
            id: "publication_date-input", 
            class: "form-control" %> 
    </div>

    <div class="form-group mb-1">
      <% is_valid_is_published = triggered_validation && errors_h[:is_published].blank? && @article.is_published.present?  %>
      <% is_invalid_is_published = !!errors_h[:is_published]  %>
      <%= form.label "is_published-input", 'Is published ?', class: "form-check-label mb-0 fw-600" %>
      <small id="hint_id_is_published" class="form-text text-muted d-block my-0">
        If checked, article will appear as public : on website, blog, RSS feed, sitemap. If not checked, the article will be only accessible via URL once created.
      </small>
      <%= form.check_box 'is_published', 
            value: @article.is_published, 
            id: "is_published-input", 
            class: "form-check-input #{"is-invalid" if is_invalid_is_published} #{"is-valid" if is_valid_is_published}", aria: ({ invalid: is_invalid_is_published, describedby: "is_published_message" } if triggered_validation ) %> 
      <%= content_tag(:span, errors_h[:is_published][0], class: "invalid-feedback", id: "is_published_message") if is_invalid_is_published %>
      <%= content_tag(:span, 'looks good !', class: "valid-feedback", id: "is_published_message") if is_valid_is_published  %>
    </div>
 
    <div class="form-group mb-1">
      <%= form.label "tags-input", 'Tags', class: "mb-0 fw-600" %>
      <small id="hint_id_articles" class="form-text text-muted d-block my-0">
        Optional : list tags for this article.
      </small>
      <%= form.select :tag_ids, Tag.all.collect {|e| [ e.shortname, e.id ] }, {}, {:multiple => true, :class => "tom-select-it form-control", :style => "width:450px;" } %>
    </div>


  </div>

  <div class="justify-content-between">
    <div class="my-4">
      <%= form.submit class: 'btn btn-primary btn btn-dark btn-sm px-2 me-2' %>
      <%= link_to 'Back', admin_articles_path, class: "btn bg-white btn-sm px-2" %>
    </div>
  </div>
<% end %>

<% content_for :custom_stylesheet do %>
  <link rel="stylesheet" href="https://uicdn.toast.com/editor/3.1.2/toastui-editor.min.css">
<% end %>
<% content_for :custom_javascript do %>
  <script src="https://uicdn.toast.com/editor/3.1.2/toastui-editor-all.min.js"></script>
  <script>
    document.addEventListener("DOMContentLoaded", function(event) { 
      const Editor = toastui.Editor;
      let initValue = "<%= escape_javascript @article.kontent.try(:html_safe) %>"
      initValue = initValue.replace(/\\k/g,'\n');
      window.kontent_editor = new Editor({
        el: document.querySelector('#editorSection'),
        initialEditType: 'markdown',
        initialValue: initValue,
        previewStyle: 'vertical',
        height: '300px'
      });
      kontent_editor.on('change', () => {
        document.getElementById('kontent-input').setAttribute('value', kontent_editor.getMarkdown().replace(/(?:\r\n|\r|\n)/g, '\\k'));
      })
    });
  </script>
<% end %>

<% content_for :custom_stylesheet do %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tom-select/2.0.0/css/tom-select.bootstrap5.min.css" integrity="sha512-UJy/ItiveaheFLF2h77Suzq5Y31Pd51KxYMhyJqManLy2PxqA9ZdbszEPdUk3g/IQeQ/hzrtMIaM/PppFnuDEw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<% end %>
<% content_for :custom_javascript do %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tom-select/2.0.0/js/tom-select.complete.min.js" integrity="sha512-tOLFqPdA0O93P0d+3NeGC2GeMAa0JpxON85laCKKTM+DN9XnBYAWPwaxGvrpsF35q9mWkZoGcji6MqYPPdMMsw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script>
    document.addEventListener("DOMContentLoaded", function(event) { 
      var config = {
        allowEmptyOption: true,
        maxItems: null, // The max number of items the user can select. 1 makes the control mono-selection, null allows an unlimited number of items.
        items: [
        <% @article.tags.each do |tag| %>
          <%= tag.id %>,
        <% end %>
        ]
      };
      new TomSelect('.tom-select-it', config);
    })
  </script> 
<% end %>

app/views/admin/articles/index.html.erb
<div class="container">
  <div class="row mb-3">
    <div class="col-12 col-lg-5 justify-content-start align-items-start mb-lg-2">
      <h2 class="mb-2 mb-lg-0 fw-bold truncate h3">
        Articles
      </h2>
    </div>
    <div class="col-12 col-lg-auto flex-1 ms-auto justify-content-center align-items-end mb-lg-2">
      <%= render 'actions', being: 'index' %>
    </div>
  </div>
  <div class="card p-0 p-sm-3 p-lg-4 flex-column justify-content-center align-items-between mb-2">
    <table class="table admin-table-index">
      <thead>
        <tr>
          <th class="d-none d-sm-table-cell">Id</th>
          <th class="d-none d-lg-table-cell">Slug</th>
          <th class="d-none d-lg-table-cell">Publication date</th>
          <th class="d-none d-lg-table-cell">Already published?</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @articles.each do |article| %>
          <tr>
            <td class="d-none d-sm-table-cell">
              <%= article.id %>
            </td>
            <td class="d-none d-lg-table-cell">
              <%= article.slug %>
            </td>                  
            <td class="d-none d-lg-table-cell">
              <%= article.publication_date.try(:strftime, "%B %d, %Y") %>
            </td>                  
            <td class="d-none d-lg-table-cell">
              <%= article.is_published %>
            </td>                  
            <td>
              <div class="d-flex d-flex justify-content-end">
                <%= link_to [:admin, article], :class => "d-flex justify-content-center align-items-center btn btn-sm btn-ghost ms-1" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                    <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"></path>
                    <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"></path>
                  </svg>
                  <span class="ms-1 d-none d-lg-block">Show</span>
                <% end %>
                <%= link_to edit_admin_article_path(article), :class => "d-flex justify-content-center align-items-center btn btn-sm btn-ghost ms-1" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"></path>
                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"></path>
                  </svg>
                  <span class="ms-1 d-none d-lg-block">Edit</span>
                <% end %>
                <%= form_with url: admin_article_path(article.id), method: :delete, data: { turbo: false } do |form| %>
                  <%= form.submit 'Destroy', class: "admin-destroy-item d-flex justify-content-center align-items-center btn btn-sm btn-ghost ms-1 d-none d-lg-block", style: "padding-left: 1.35rem" %>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/articles/show.html.erb
<div class="container">
  <div class="row mb-3">
    <div class="col-12 col-lg-5 justify-content-start align-items-start mb-lg-2">
      <h1 class="mb-2 mb-lg-0 fw-bold truncate h3">
        Show Article
      </h1>
    </div>
    <div class="col-12 col-lg-auto flex-1 ms-auto justify-content-center align-items-end mb-lg-2">
      <%= render 'actions', being: 'show', article: @article %>
    </div>
  </div>
  <div class="card p-3 p-lg-4 flex-column justify-content-center align-items-between mb-2">
    <div class="container-fluid">
      <dl class="mb-4">
        <dt class="">Id</dt>
        <dd class="fs-small text-muted m-0">Technical ID in the database</dd>
        <dd class=""><%= @article.id %></dd>
      </dl>
      <dl class="mb-4">
        <dt class="">Slug</dt>
        <dd class="fs-small text-muted m-0">String ID, url-compatible</dd>
        <dd class=""><%= @article.slug.present? ? @article.slug : '<not set>' %></dd>
      </dl>
      <dl class="mb-4">
        <dt class="">Content</dt>
        <dd class="fs-small text-muted m-0">Actual content of your article</dd>
        <dd class=""><%= @article.kontent.present? ? @article.kontent.to_s[0, 240] : '<not set>' %></dd>
      </dl>
      <dl class="mb-4">
        <dt class="">Title</dt>
        <dd class="fs-small text-muted m-0">Title of your article, as it will appear in SEO results and tab title</dd>
        <dd class=""><%= @article.title.present? ? @article.title.to_s[0, 240] : '<not set>' %></dd>
      </dl>
      <dl class="mb-4">
        <dt class="">Description</dt>
        <dd class="fs-small text-muted m-0">Description of the article, as it will appear in SEO results</dd>
        <dd class=""><%= @article.description.present? ? @article.description.to_s[0, 240] : '<not set>' %></dd>
      </dl>
      <dl class="mb-4">
        <dt class="">Image URL</dt>
        <dd class="fs-small text-muted m-0">URL of the image of the article, as it will appear when you share it on social medias.</dd>
        <dd class=""><%= @article.image_url.present? ? @article.image_url : '<not set>' %></dd>
      </dl>
      <dl class="mb-4">
        <dt class="">Publication date</dt>
        <dd class="fs-small text-muted m-0">Will appear as the creation date of the article.</dd>
        <dd class=""><%= @article.publication_date.present? ? @article.publication_date.strftime("%A %d %b %Y %H:%M:%S") : '<not set>' %></dd>
      </dl>
      <dl class="mb-4">
        <dt class="">Creation date</dt>
        <dd class="fs-small text-muted m-0">Creation date in the database.</dd>
        <dd class=""><%= @article.created_at.strftime("%A %d %b %Y %H:%M:%S") %></dd>
      </dl>
      <dl class="mb-4">
        <dt class="">Updated at</dt>
        <dd class="fs-small text-muted m-0">Last time it was update in the database.</dd>
        <dd class=""><%= @article.updated_at.strftime("%A %d %b %Y %H:%M:%S") %></dd>
      </dl>
      <dl class="mb-4">
        <dt class="">Tags</dt>
        <dd class="fs-small text-muted m-0">Tags for this article.</dd>
        <dd class=""><%= @article.tags.present? ? @article.tags.map(&:shortname).join(', ') : '<not set>' %></dd>
      </dl>

      <%= link_to 'Edit', edit_admin_article_path(@article), class: "btn btn-primary btn btn-dark btn-sm px-3" %>
      <%= link_to 'Back', admin_articles_path, class: "btn bg-white btn-sm px-3" %>
    </div>
  </div>
</div>