config/routes.rb
Rails.application.routes.draw do
  resources :entities
  resources :dna_codes

  # Sitemap
  get '/sitemap.xml' => 'sitemaps#index', defaults: { format: 'xml' }

  # Feed
  get '/feed', to: 'feeds#rss', format: 'xml', as: :feed

  # Error pages
  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unacceptable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  # Admin dashboard
  namespace :admin do
    # Monitoring tools
    get 'monitoring', to: 'monitorings#index'
    resource :helloworld_job, only: [:create, :show]
    resource :migrate_data, only: [:edit, :update, :show]
    resource :versions, only: [:show]
    # CRUD our data
    resources :accounts
    resources :articles
    resources :editables
    resources :tags
    # Settings accessible to non-techies
    resources :settings, only: [:index, :update]
    # Home page of the admin
    root :to => "admin#index"
  end

  # Customer dashboard
  namespace :profile do
    root :to => "names#show"
    resource :name, only: [:show, :update]
    resource :danger, only: [:show]
    resource :preference, only: [:show, :update]
    resource :billing, only: [:show]
  end
  
  # Routes are protected under app/misc/rodauth_app.rb
  mount Sidekiq::Web => '/admin/monitor/jobs', :as => 'sidekiq'
  mount RailsDb::Engine => '/admin/monitor/db', :as => 'rails_db'

  # Public pages
  get "home/index"
  root to: "home#index"
  get "terms", to: "page#terms"
  get "about", to: "page#about"
  get "faq", to: "page#faq"
  get "credits", to: "page#credits"
  get "styleguide", to: "page#styleguide"
  get "pricing", to: "page#pricing"
  get "changelog", to: "page#changelog"

  # Blog
  namespace :blog do
    resources :tags, only: [:index, :show]
  end
  resources :blog, only: [:index, :show]

  # Test-mode only routes
  get "/get_last_email", to: "test#get_last_email" if Rails.env.test?
end

app/models/dna_code.rb
class DnaCode < ApplicationRecord
	belongs_to :account
	before_save :modify_dna_string
	validates_presence_of :account_id, :raw


	def modify_dna_string
		self.raw = self.raw.gsub("\n", "")
		self.raw = self.raw.gsub("\r", "")
		self.raw = self.raw.gsub(" ", "")
		self.raw = self.raw.downcase
	end
end

app/controllers/dna_codes_controller.rb
class DnaCodesController < ApplicationController
  before_action :set_dna_code, only: %i[ show edit update destroy ]
  skip_verify_authorized

  # GET /dna_codes
  def index
    @dna_codes = DnaCode.all
  end

  # GET /dna_codes/1
  def show
    @base_pairs = params[:base_pairs]&.to_i

    unless @base_pairs.blank?
      end_range = @base_pairs - 1
      @dna_array = @dna_code.raw.chars.each_with_index.map { |v,i| @dna_code.raw[i..i+end_range] }
    end
      respond_to do |format|
        format.xlsx {
          response.headers[
            'Content-Disposition'
          ] = "attachment; filename=dna.xlsx"
        }
        format.html { render :show }
      end


  end

  # GET /dna_codes/new
  def new
    @dna_code = DnaCode.new
  end

  # GET /dna_codes/1/edit
  def edit
  end

  # POST /dna_codes
  def create
    @dna_code = DnaCode.new(dna_code_params)

    if @dna_code.save
      redirect_to @dna_code, notice: "Dna code was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /dna_codes/1
  def update
    if @dna_code.update(dna_code_params)
      redirect_to @dna_code, notice: "Dna code was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /dna_codes/1
  def destroy
    @dna_code.destroy
    redirect_to dna_codes_url, notice: "Dna code was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dna_code
      @dna_code = DnaCode.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dna_code_params
      params.require(:dna_code).permit(:raw, :account_id, :entity_id, :base_pairs, :gene_name)
    end
end

app/helpers/dna_codes_helper.rb
module DnaCodesHelper
end

app/views/dna_codes/_dna_code.html.erb
<div id="<%= dom_id dna_code %>">
  <p class="pre" style="word-wrap: break-word;">
    <strong>Raw:</strong>
    <%= dna_code.raw %>
  </p>



</div>

app/views/dna_codes/_form.html.erb
<%= form_with(model: dna_code) do |form| %>
  <% if dna_code.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dna_code.errors.count, "error") %> prohibited this dna_code from being saved:</h2>

      <ul>
        <% dna_code.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :gene_name, style: "display: block"%>
    <%= form.text_field :gene_name,  class: "form-control" %>
  </div>
  <div>
    <%= form.label :raw, style: "display: block" %>
    <%= form.text_area :raw, class: "form-control" %>
  </div>

  <div>
    <% options = options_from_collection_for_select(Profile.all, 'account_id', 'name') %>
    
    <%= form.label :account_id, "Patient", style: "display: block" %>
    <%= form.select :account_id,  options, class: "form-control" %>
  </div>



  <div>
    <%= form.submit class: "btn btn-dark btn-sm mt-3" %>
  </div>
<% end %>

app/views/dna_codes/edit.html.erb
<h1>Editing dna code</h1>

<%= render "form", dna_code: @dna_code %>

<br>

<div>
  <%= link_to "Show this dna code", @dna_code %> |
  <%= link_to "Back to dna codes", dna_codes_path %>
</div>

app/views/dna_codes/index.html.erb
<p style="color: green"><%= notice %></p>
	<h1>DNA Sequences</h1>

	<div id="dna_codes">
	  <table class="table">
	  	<thead>
	  		<tr>
	  			<th>Gene</th>
	  			<th>Patient</th>
	  			<th>Created At</th>
	  			<th>Actions</th>
	  		</tr>
	  	</thead>
	  	<tbody>
		  <% @dna_codes.each do |dna_code| %>
	    	<tr>
	    		<td><%= link_to dna_code.gene_name, dna_code %></td>
	    		<td><%=dna_code.account.profile.name%></td>
	    		<td><%= dna_code.created_at %></td>
	    		<td>
	    			<%= link_to "Edit", edit_dna_code_path(dna_code) %> |
  					<%= link_to "Delete", @dna_code, method: :delete %>
	    		</td>
	    	</tr>
	  <% end %>
	  	</tbody>
	  </table>

	</div>

	<%= link_to "New dna sequence", new_dna_code_path %>

app/views/dna_codes/new.html.erb
<h1>New dna code</h1>

<%= render "form", dna_code: @dna_code %>

<br>

<div>
  <%= link_to "Back to dna codes", dna_codes_path %>
</div>

app/views/dna_codes/show.html.erb
<p style="color: green"><%= notice %></p>

<h3>Gene: <%= !@dna_code.gene_name.nil? ? @dna_code.gene_name : "Undefined" %></h3>
<form>
  <label><b>Number of base pairs</b></label><br />
  <%= text_field_tag :base_pairs, params[:base_pairs] %>
  <%= submit_tag 'Submit', :name => nil, class: "btn btn-dark btn-sm" %>

</form>

<p class="text-end">
	<%=
	  link_to 'Download as Excel',
	  params.permit(:base_pairs).merge(format: :xlsx), class: "btn btn-dark btn-sm"
	%>
	<%= link_to "Back", dna_codes_path, class: "btn btn-light btn-sm" %>
</p>

<br />
<div class="container">
	<div class="row">
		<div class="col col-md-6">
		  <%= render @dna_code %>
		</div>
		<div class="col col-md-6">
		  <% unless @dna_array.blank? %>
			<table class="table">
				<thead>
					<tr>
						<th>seq</th>
						<th>A</th>
						<th>C</th>
						<th>G</th>
						<th>T</th>
					</tr>
				</thead>
				<tbody>
					<% @dna_array.each do |d| %>
						<tr>
							<td><%= d %></td>
							<td><%= d.count('a') %></td>
							<td><%= d.count('c') %></td>
							<td><%= d.count('g') %></td>
							<td><%= d.count('t') %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		  <% end %>
		</div>
	</div>
</div>





<div>
  

</div>