config/routes.rb
Rails.application.routes.draw do
  resources :entities
  resources :dna_codes

  # Sitemap
  get '/sitemap.xml' => 'sitemaps#index', defaults: { format: 'xml' }

  # Feed
  get '/feed', to: 'feeds#rss', format: 'xml', as: :feed

  # Error pages
  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unacceptable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  # Admin dashboard
  namespace :admin do
    # Monitoring tools
    get 'monitoring', to: 'monitorings#index'
    resource :helloworld_job, only: [:create, :show]
    resource :migrate_data, only: [:edit, :update, :show]
    resource :versions, only: [:show]
    # CRUD our data
    resources :accounts
    resources :articles
    resources :editables
    resources :tags
    # Settings accessible to non-techies
    resources :settings, only: [:index, :update]
    # Home page of the admin
    root :to => "admin#index"
  end

  # Customer dashboard
  namespace :profile do
    root :to => "names#show"
    resource :name, only: [:show, :update]
    resource :danger, only: [:show]
    resource :preference, only: [:show, :update]
    resource :billing, only: [:show]
  end
  
  # Routes are protected under app/misc/rodauth_app.rb
  mount Sidekiq::Web => '/admin/monitor/jobs', :as => 'sidekiq'
  mount RailsDb::Engine => '/admin/monitor/db', :as => 'rails_db'

  # Public pages
  get "home/index"
  root to: "home#index"
  get "terms", to: "page#terms"
  get "about", to: "page#about"
  get "faq", to: "page#faq"
  get "credits", to: "page#credits"
  get "styleguide", to: "page#styleguide"
  get "pricing", to: "page#pricing"
  get "changelog", to: "page#changelog"

  # Blog
  namespace :blog do
    resources :tags, only: [:index, :show]
  end
  resources :blog, only: [:index, :show]

  # Test-mode only routes
  get "/get_last_email", to: "test#get_last_email" if Rails.env.test?
end

app/models/account.rb
class Account < ApplicationRecord
  include Rodauth::Rails.model
    
  ROLE = {
    admin: "admin",
    customer: "customer",
  }    

  has_one :profile, dependent: :destroy
  accepts_nested_attributes_for :profile

  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  # The validation of password here is only for the following scenario :
  # An admin creates a new Account in the /admin dashboard.
  # 
  # Security of password of customers, in the "Sign up" screen, is a lot more secure.
  # See :password_complexity in class RodauthMain. Documented here :
  # http://rodauth.jeremyevans.net/rdoc/files/doc/password_complexity_rdoc.html
  validates :password, presence: true, on: :create, format: { with: /\A(?=.{8,})/x, message: "Must contain 8+ characters" }
    

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  
  validates :slug, presence: true, uniqueness: true
  validates_format_of :slug, with: /\A[-_A-Za-z0-9]+\z/, message: "invalid : alphanumeric characters only"

  validates :title, presence: true, uniqueness: true, length: {minimum: 5, maximum: 120}

  validates :image_url, allow_blank: true, format: { with: URI.regexp(%w[http https]), message: 'is not a valid URL' }

  # Many-to-many relationship between tags and articles
  has_many :markers
  has_many :tags, through: :markers

end

app/models/dna_code.rb
class DnaCode < ApplicationRecord
	belongs_to :account
	before_save :modify_dna_string
	validates_presence_of :account_id, :raw


	def modify_dna_string
		self.raw = self.raw.gsub("\n", "")
		self.raw = self.raw.gsub("\r", "")
		self.raw = self.raw.gsub(" ", "")
		self.raw = self.raw.downcase
	end
end

app/models/editable.rb
class Editable < ApplicationRecord
  
  validates :shortname, presence: true, uniqueness: true, length: {minimum: 3, maximum: 120}
  validates_format_of :shortname, with: /\A[-_A-Za-z0-9]+\z/, message: "invalid : alphanumeric characters only"

end

app/models/entity.rb
class Entity < ApplicationRecord
end

app/models/marker.rb
class Marker < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :account, optional: true
  validates :name, presence: true, length: {minimum: 3, maximum: 42}

  def self.marketing_preferences
    {
      newsletter: 'Subscribe to newsletter (four times a month)',
      courses: 'Subscribe to Ruby-on-Rails courses',
      surveys: 'I accept to be contacted for surveys',
    }
  end

  def self.report_preferences
    {
      weekly: 'Every week',
      monthly: 'Every month',
      yearly: 'Every year',
      never: 'Never',
    }
  end

end

app/models/setting.rb
# Only one row for this record, in order to handle global (but dynamic) settings,
# Like the website title (for SEO) or website description (also for SEO)
class Setting < ApplicationRecord
  before_create :only_one_row

  validates :clock_diff, presence: true, numericality: { only_integer: true }

  private
  
  def only_one_row
    raise "You can create only one row of this table" if Setting.count > 0
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  
  validates :shortname, presence: true, uniqueness: true
  validates_format_of :shortname, with: /\A[-_A-Za-z0-9]+\z/, message: "invalid : alphanumeric characters only"

  validates :display_name, presence: true, uniqueness: true, length: {minimum: 3, maximum: 80}
  validates_format_of :display_name, with: /\A[a-zA-Z0-9\s]+\z/i, message: "invalid : can only contain letters, spaces, and numbers."

  # Many-to-many relationship between tags and articles
  has_many :markers
  has_many :articles, through: :markers, dependent: :delete_all

end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

  skip_verify_authorized
  
  def index
    @articles = GetArticleList.new.call
  end

  def show
    if Setting.first.shareable_draft == true
      @article = GetArticle.new.call(params[:id])
    else
      raise ActionController::RoutingError.new('Not Found')
    end
  end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController

  skip_verify_authorized

  def not_found
  end

  def unacceptable
  end

  def internal_server_error
  end
  
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

  skip_verify_authorized

  layout false

  def rss
    @articles = Article.where(is_published: true).order("created_at DESC")
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_verify_authorized

  def index
    @quote_of_landing_page = GetEditable.new.call('quote-of-landing-page')
  end

end

app/controllers/page_controller.rb
class PageController < ApplicationController

  skip_verify_authorized

  def terms
    @terms_and_conditions = GetEditable.new.call('terms-and-conditions')
  end

end

app/controllers/test_controller.rb
#
# This controller is meant to be used in test mode only.
#
class TestController < ApplicationController

  skip_verify_authorized

  def get_last_email
    render json: {
      mail: ActionMailer::Base.deliveries.try(:last).try(:body).try(:decoded)
    } 
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dna_codes_helper.rb
module DnaCodesHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? "#{content_for(:meta_title)} | #{DEFAULT_META['meta_title']}" : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
  end
end

app/views/admin/admin/index.html.erb
<div class="container">
  <div class="row mb-3">
    <div class="col-12 col-lg-5 justify-content-start align-items-start mb-lg-2">
      <h1 class="mb-2 mb-lg-0 fw-bold truncate h3">
        Welcome to the admin dashboard
      </h1>
    </div>
  </div>
  <div class="mt-4">
    <h2 class="h5">KPIs</h2>
  </div>
  <div class="row justify-content-between gx-3">
    <div class="col-12 col-md-6 col-lg-3 mb-3" style="height: 96px;">
      <div class="card w-100 h-100 d-flex flex-column p-3">
        <div class="d-flex justify-content-start align-items-center">
          <p class="flex-center mb-0 fs-small" style="font-weight: 500;">
            <span class="cursor-pointer">
              <span class="truncate flex-center">Key indicator n°1 
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="12" height="12" fill="currentColor" class="ms-1 text-muted" data-bs-toggle="popover" title="Popover title" data-bs-content="Some text">
                  <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z">
                  </path>
                </svg>
              </span>
            </span>
          </p>
        </div>
        <div class="my-auto d-flex">
          <h5 class="text-nowrap d-flex flex-row justify-content-center align-items-end m-0">
            <span class="d-flex flex-row fw-bold">1.81s<div class="flex-center flex-row text-danger ms-2" style="font-weight: 500; font-size: 12px;">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="18" height="18" fill="currentColor">
                  <path fill-rule="evenodd" d="M8 12a.5.5 0 0 0 .5-.5V5.707l2.146 2.147a.5.5 0 0 0 .708-.708l-3-3a.5.5 0 0 0-.708 0l-3 3a.5.5 0 1 0 .708.708L7.5 5.707V11.5a.5.5 0 0 0 .5.5z">
                  </path>
                </svg>
                <span>3.7%</span>
              </div>
            </span>
          </h5>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-6 col-lg-3 mb-3" style="height: 96px;">
      <div class="card w-100 h-100 d-flex flex-column p-3">
        <div class="d-flex justify-content-start align-items-center">
          <p class="flex-center mb-0 fs-small" style="font-weight: 500;">
            <span class="cursor-pointer">
              <span class="truncate flex-center">Key indicator n°2
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="12" height="12" fill="currentColor" class="ms-1 text-muted" data-bs-toggle="popover" title="Popover title" data-bs-content="Some text">
                  <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z">
                  </path>
                </svg>
              </span>
            </span>
          </p>
        </div>
        <div class="my-auto d-flex">
          <h5 class="text-nowrap d-flex flex-row justify-content-center align-items-end m-0">
            <span class="d-flex flex-row fw-bold">2.04s<div class="flex-center flex-row text-danger ms-2" style="font-weight: 500; font-size: 12px;">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="18" height="18" fill="currentColor">
                  <path fill-rule="evenodd" d="M8 12a.5.5 0 0 0 .5-.5V5.707l2.146 2.147a.5.5 0 0 0 .708-.708l-3-3a.5.5 0 0 0-.708 0l-3 3a.5.5 0 1 0 .708.708L7.5 5.707V11.5a.5.5 0 0 0 .5.5z">
                  </path>
                </svg>
                <span>1.4%</span>
              </div>
            </span>
          </h5>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-6 col-lg-3 mb-3" style="height: 96px;">
      <div class="card w-100 h-100 d-flex flex-column p-3">
        <div class="d-flex justify-content-start align-items-center">
          <p class="flex-center mb-0 fs-small" style="font-weight: 500;">
            <span class="cursor-pointer">
              <span class="truncate flex-center">Key indicator n°3
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="12" height="12" fill="currentColor" class="ms-1 text-muted" data-bs-toggle="popover" title="Popover title" data-bs-content="Some text">
                  <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z">
                  </path>
                </svg>
              </span>
            </span>
          </p>
        </div>
        <div class="my-auto d-flex">
          <h5 class="text-nowrap d-flex flex-row justify-content-center align-items-end m-0">
            <span class="d-flex flex-row fw-bold">0.19s<div class="flex-center flex-row text-success ms-2" style="font-weight: 500; font-size: 12px;">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="18" height="18" fill="currentColor">
                  <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v5.793l2.146-2.147a.5.5 0 0 1 .708.708l-3 3a.5.5 0 0 1-.708 0l-3-3a.5.5 0 1 1 .708-.708L7.5 10.293V4.5A.5.5 0 0 1 8 4z">
                  </path>
                </svg>
                <span>-0.5%</span>
              </div>
            </span>
          </h5>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-6 col-lg-3 mb-3" style="height: 96px;">
      <div class="card w-100 h-100 d-flex flex-column p-3">
        <div class="d-flex justify-content-start align-items-center">
          <p class="flex-center mb-0 fs-small" style="font-weight: 500;">
            <span class="cursor-pointer">
              <span class="truncate flex-center">Key indicator n°4
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="12" height="12" fill="currentColor" class="ms-1 text-muted" data-bs-toggle="popover" title="Popover title" data-bs-content="Some text">
                  <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z">
                  </path>
                </svg>
              </span>
            </span>
          </p>
        </div>
        <div class="my-auto d-flex">
          <h5 class="text-nowrap d-flex flex-row justify-content-center align-items-end m-0">
            <span class="d-flex flex-row fw-bold">0.78s<div class="flex-center flex-row text-success ms-2" style="font-weight: 500; font-size: 12px;">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="18" height="18" fill="currentColor">
                  <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v5.793l2.146-2.147a.5.5 0 0 1 .708.708l-3 3a.5.5 0 0 1-.708 0l-3-3a.5.5 0 1 1 .708-.708L7.5 10.293V4.5A.5.5 0 0 1 8 4z">
                  </path>
                </svg>
                <span>-3.1%</span>
              </div>
            </span>
          </h5>
        </div>
      </div>
    </div>
  </div>
  <div class="mt-4">
    <h2 class="h5">Resources</h2>

    <div class="card p-4 mb-2 flex-column flex-md-row justify-content-between align-items-start align-items-md-center">
      <div class="d-flex flex-row justify-content-start align-items-center flex-1 mb-3 mb-md-0">
        <div class="d-flex flex-row justify-content-start align-items-center">
          <img class="me-3" style="min-width: 18px" width="18" height="18" src="https://assets.panelbear.com/static/icons/check-circle-fill.75b38293bef4.svg">
          <p class="fw-bold text-dark mb-0">Articles</p>
        </div>
      </div>
      <div class="d-flex flex-row justify-content-center align-items-center">
        <p class="mb-0 me-3 mx-md-3 fs-small text-muted d-none d-md-block">
          Blog articles, viewables under /blog.
        </p>
        <div style="min-width: 100px" class="d-flex flex-row justify-content-between align-items-center">
          <%= link_to 'New', new_admin_article_path, class: "btn btn-sm bg-white" %>
          <%= link_to 'List', admin_articles_path, class: "btn btn-sm bg-white" %>
        </div>
      </div>
    </div>

    <div class="card p-4 mb-2 flex-column flex-md-row justify-content-between align-items-start align-items-md-center">
      <div class="d-flex flex-row justify-content-start align-items-center flex-1 mb-3 mb-md-0">
        <div class="d-flex flex-row justify-content-start align-items-center">
          <img class="me-3" style="min-width: 18px" width="18" height="18" src="https://assets.panelbear.com/static/icons/check-circle-fill.75b38293bef4.svg">
          <p class="fw-bold text-dark mb-0">Tags</p>
        </div>
      </div>
      <div class="d-flex flex-row justify-content-center align-items-center">
        <p class="mb-0 me-3 mx-md-3 fs-small text-muted d-none d-md-block">
          Categories of the blog articles.
        </p>
        <div style="min-width: 100px" class="d-flex flex-row justify-content-between align-items-center">
          <%= link_to 'New', new_admin_tag_path, class: "btn btn-sm bg-white" %>
          <%= link_to 'List', admin_tags_path, class: "btn btn-sm bg-white" %>
        </div>
      </div>
    </div>

    <div class="card p-4 mb-2 flex-column flex-md-row justify-content-between align-items-start align-items-md-center">
      <div class="d-flex flex-row justify-content-start align-items-center flex-1 mb-3 mb-md-0">
        <div class="d-flex flex-row justify-content-start align-items-center">
          <img class="me-3" style="min-width: 18px" width="18" height="18" src="https://assets.panelbear.com/static/icons/check-circle-fill.75b38293bef4.svg">
          <p class="fw-bold text-dark mb-0">Accounts</p>
        </div>
      </div>
      <div class="d-flex flex-row justify-content-center align-items-center">
        <p class="mb-0 me-3 mx-md-3 fs-small text-muted d-none d-md-block">
          Users of this application.
        </p>
        <div style="min-width: 100px" class="d-flex flex-row justify-content-between align-items-center">
          <%= link_to 'New', new_admin_account_path, class: "btn btn-sm bg-white" %>
          <%= link_to 'List', admin_accounts_path, class: "btn btn-sm bg-white" %>
        </div>
      </div>
    </div>

    <div class="card p-4 mb-2 flex-column flex-md-row justify-content-between align-items-start align-items-md-center">
      <div class="d-flex flex-row justify-content-start align-items-center flex-1 mb-3 mb-md-0">
        <div class="d-flex flex-row justify-content-start align-items-center">
          <img class="me-3" style="min-width: 18px" width="18" height="18" src="https://assets.panelbear.com/static/icons/check-circle-fill.75b38293bef4.svg">
          <p class="fw-bold text-dark mb-0">Editables</p>
        </div>
      </div>
      <div class="d-flex flex-row justify-content-center align-items-center">
        <p class="mb-0 me-3 mx-md-3 fs-small text-muted d-none d-md-block">
          HTML that can be edited. Full page, or only parts.
        </p>
        <div style="min-width: 100px" class="d-flex flex-row justify-content-between align-items-center">
          <%= link_to 'New', new_admin_editable_path, class: "btn btn-sm bg-white" %>
          <%= link_to 'List', admin_editables_path, class: "btn btn-sm bg-white" %>
        </div>
      </div>
    </div>


  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="container mt-5 pt-5" style="max-width: 1280px;">
    <div class="row">
        <div class="col-12 d-flex flex-column mb-5 col-lg-4">
            <p class="mb-3 fw-700 text-dark">Everlum Bio</p>
            <p class="gray-600 pe-5">At Everlum we beleive that everyone deserves a cure no matter how big or small the disease.  We are working on inovating products to make this a reality.</p>
        </div>
        <div class="col-12 d-flex flex-column mb-5 col-lg">
            <p class="mb-3 fw-700 text-dark">Resources</p>
            <a class="mb-2 fs-small fw-600 gray-600" rel="noopener" href="/blog">Blog</a>
            <a class="mb-2 fs-small fw-600 gray-600" rel="noopener" href="/styleguide">Styleguide</a>
            <a class="mb-2 fs-small fw-600 gray-600" rel="noopener" href="/changelog">Changelog</a>
          <!--   <a class="mb-2 fs-small fw-600 gray-600" rel="noopener" href="/feed">RSS feed</a>
            <a class="mb-2 fs-small fw-600 gray-600" rel="noopener" href="/sitemap.xml" target="_blank">Sitemap</a> -->
        </div>
        <div class="col-12 d-flex flex-column mb-5 col-lg">
            <p class="mb-3 fw-700 text-dark">Product</p>
            <a class="mb-2 fs-small fw-600 gray-600" rel="noopener" href="/about">About</a>
            <a class="mb-2 fs-small fw-600 gray-600" rel="noopener" href="/pricing">Pricing</a>
          <!--   <a class="mb-2 fs-small fw-600 gray-600" rel="noopener" href="/credits">Credits</a> -->
            <a class="mb-2 fs-small fw-600 gray-600" rel="noopener" href="/faq">FAQ</a>
        </div>
        <div class="col-12 d-flex flex-column mb-5 col-lg">
            <p class="mb-3 fw-700 text-dark">Shorcuts</p>
 <!--            <a class="mb-2 fs-small fw-600 gray-600" rel="noopener" href="/login">Log in</a> -->
            <a class="mb-2 fs-small fw-600 gray-600" rel="noopener" href="/create-account">Sign up</a>
            <a class="mb-2 fs-small fw-600 gray-600" rel="noopener" href="/terms">Terms and conditions</a>
            
        </div>
    </div>
    <div class="row">
        <div class="col-12 d-flex flex-column mb-5 col-md-6">
            <div class="d-flex flex-column justify-content-start align-items-start">
                <p class="m-0 text-muted small mb-3"> © 2023 <a href="https://bootrails.com" class="fw-normal text-muted">Everlum Bio</a>. All rights reserved.</p>
            </div>
        </div>
        <div class="col-12 d-flex flex-column mb-5 col-md-6 justify-content-end align-items-start align-items-md-end">
            <p class="text-muted small flex-center pe-3">Need help? <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="18" height="18" fill="currentColor">
                    <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z">
                    </path>
                </svg> <a class="text-muted fw-bold" href="mailto:<%=ENV['APP_EMAIL_HELP']%>?subject=Help" id="bottom"><%=ENV['APP_EMAIL_HELP']%></a>
            </p>
        </div>
    </div>
</footer>

app/views/shared/_logo.html.erb
<a class="navbar-brand me-5" href="/" style="margin-top: -.22rem;"><img src="https://everlum.bio/hs-fs/hubfs/lydia_1.3.png?width=1669&name=lydia_1.3.png" style="max-width: 175px;"></a>

app/views/shared/_main_nav.html.erb
<header class="container" style="max-width: 1280px;">
  <nav class="navbar navbar-expand-lg navbar-light bg-white mt-1">
    <div class="container-fluid">
      <%= render 'shared/logo'  %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#actualNavbar" aria-controls="actualNavbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="actualNavbar">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
<!--           <li class="nav-item px-2">
            <a class="nav-link fw-500" aria-current="page" href="/blog">Resources</a>
          </li> -->
          <%# if !rodauth.logged_in? %>
<!--           <li class="nav-item px-2">
            <a class="nav-link fw-500" aria-current="page" href="/about">About</a>
          </li>
          <li class="nav-item px-2">
            <a class="nav-link fw-500" aria-current="page" href="/pricing">Pricing</a>
          </li> -->
          <%# else %>
            <li class="nav-item px-2">
            <a class="nav-link fw-500" aria-current="page" href="/dna_codes">DNA Explorer</a>
          </li>
          <%# end %>
        </ul>
        <div class="ms-auto navbar-nav">
          <% if rodauth.logged_in? %>
            <% if allowed_to?(:index?, :admin) %>
              <li><a class="nav-link fw-500 me-3 px-2" href="/admin">Admin</a></li>
            <% end %>
            <%= link_to "Profile", profile_root_path, class:"nav-link fw-500 me-3 px-2" %>
            <%= form_with url: rodauth.logout_path, method: :post, data: { turbo: false } do |form| %>
              <%= form.submit rodauth.logout_button, class: "nav-link fw-500 border-0 bg-white me-4 ms-2 ms-lg-0 mb-2 mb-lg-0 " %>
            <% end %>
          <% else %>
            <%= link_to "Sign up", rodauth.create_account_path, class:"nav-link fw-500 me-3 px-2" %>
            <%= link_to "Sign in", rodauth.login_path, class:"nav-link fw-500 me-4 px-2" %>
          <% end %>

        </div>
      </div>
  </nav>
</header>

app/views/shared/_profile_secondary_nav.html.erb
<nav class="secondarynav bg-light mt-3 flex-center border-bottom" style="min-height: 48px">
    <div class="container py-1">
        <div class="d-flex flex-row flex-wrap">
            <a class="btn btn-secondarynav shadow-none <%= current_page?(controller: 'names', action: 'show') ? 'active' : '' %>" href="/profile">Account</a>
            <% if allowed_to?(:show?, :customer) %>
                <%= link_to 'Preferences', profile_preference_path, class: "btn btn-secondarynav shadow-none #{current_page?(controller: 'preferences', action: 'show') ? 'active' : ''}" %>
            <% end %>
            <% if allowed_to?(:show?, :customer) %>
                <%= link_to 'Billing', profile_billing_path, class: "btn btn-secondarynav shadow-none #{current_page?(controller: 'billings', action: 'show') ? 'active' : ''}" %>
            <% end %>
            <%= link_to 'Exit', profile_danger_path, class: "btn btn-secondarynav shadow-none #{current_page?(controller: 'dangers', action: 'show') ? 'active' : ''}" %>
        </div>
    </div>
</nav>